/- Weak-Kneser plan, steps 5-6: the finite word-to-block link.

Generalizes `DensityLimit.arbitrary_progressions_of_pairs` from a single
generated point to an arbitrary finite starting set `E`, then specializes
this "grid" to a genuine bounded interval once `E` hits every residue class
modulo the pair-distance `F` (step 6's "residue-frame" argument), and
separately realizes the modular subset sums of an arbitrary finite multiset
`S` of prescribed residues as an actual finite subset (step 5's "modular
generation", consuming a modular-coverage witness `S` supplied elsewhere by
the `KneserResidues` worker rather than proving finite-cyclic-group coverage
here).

Reuses `Short/DensityLimit.FairAbsorption`/`finite_absorption` unmodified
(read-only import; `arbitrary_progressions_of_pairs` is not imported, since
`finite_grid_of_pairs` below proves the genuinely more general statement it
would otherwise be used to source). No SHARP/table/staircase machinery. -/
import Erdos1112Proof.SubsetSums
import Erdos1112Proof.Short.DensityLimit

namespace Erdos1112.Proof.Short.KneserDensity

open Erdos1112.Proof

/-- Step 6, grid-growth core: if every second component from stage `i` on
contains a pair at distance `F`, fair absorption grows an arbitrary finite
starting set `E ⊆ A i` into a full `E × [0,T]` grid (translated by a common
`base`) inside some later first component, for every `T`. Generalizes
`arbitrary_progressions_of_pairs` (there, `E` is the singleton generated by
one starting point) to an arbitrary finite `E`. -/
theorem finite_grid_of_pairs {A B : ℕ → Set ℕ} {F i : ℕ} {E : Finset ℕ}
    (hfair : FairAbsorption A B) (hmono : Monotone A) (hanti : Antitone B)
    (hE : ∀ e ∈ E, e ∈ A i) (hpairs : ∀ n ≥ i, ∃ b ∈ B n, b + F ∈ B n) :
    ∀ T, ∃ j ≥ i, ∃ base, ∀ e ∈ E, ∀ t ≤ T, base + e + F * t ∈ A j := by
  intro T
  induction T with
  | zero =>
    refine ⟨i, le_rfl, 0, fun e he t ht => ?_⟩
    have ht0 : t = 0 := by omega
    simpa [ht0] using hE e he
  | succ T ih =>
    classical
    obtain ⟨j, hji, base, hbase⟩ := ih
    let G : Finset ℕ := (Finset.range (T + 1)).biUnion (fun t => E.image (fun e => base + e + F * t))
    have hG : ∀ g ∈ G, g ∈ A j := by
      intro g hg
      obtain ⟨t, ht, hg⟩ := Finset.mem_biUnion.mp hg
      obtain ⟨e, he, rfl⟩ := Finset.mem_image.mp hg
      exact hbase e he t (by simpa [Nat.lt_succ_iff] using ht)
    obtain ⟨l, hlj, hl⟩ := finite_absorption hfair hmono hanti j G hG
    obtain ⟨b, hb, hbf⟩ := hpairs l (hji.trans hlj)
    refine ⟨l, hji.trans hlj, base + b, fun e he t ht => ?_⟩
    by_cases htT : t ≤ T
    · have hmem : base + e + F * t ∈ G :=
        Finset.mem_biUnion.mpr ⟨t, Finset.mem_range.mpr (by omega), Finset.mem_image.mpr ⟨e, he, rfl⟩⟩
      have hh := hl _ hmem b hb
      have heq : base + e + F * t + b = base + b + e + F * t := by ring
      rwa [heq] at hh
    · have heq_t : t = T + 1 := by omega
      have hmem : base + e + F * T ∈ G :=
        Finset.mem_biUnion.mpr ⟨T, Finset.mem_range.mpr (by omega), Finset.mem_image.mpr ⟨e, he, rfl⟩⟩
      have hh := hl _ hmem (b + F) hbf
      have heq : base + e + F * T + (b + F) = base + b + e + F * t := by
        rw [heq_t]; ring
      rwa [heq] at hh

/-- Step 6, residue-frame corollary: if a finite `E ⊆ A i` hits every
residue class modulo `F > 0` and every later second component contains a
pair at distance `F`, some later first component contains an entire
interval `x + [0,L)`, for every `L`. Given a target `n = U + t` (`U := max
E`), the representative `e ∈ E` of `n`'s residue class is `≤ U ≤ n`, so
`n - e` is an exact multiple of `F`; the grid lemma supplies it. -/
theorem bounded_residue_frame {A B : ℕ → Set ℕ} {F i : ℕ} {E : Finset ℕ}
    (hfair : FairAbsorption A B) (hmono : Monotone A) (hanti : Antitone B)
    (hF : 0 < F) (hE : ∀ e ∈ E, e ∈ A i) (hres : ∀ r < F, ∃ e ∈ E, e % F = r)
    (hpairs : ∀ n ≥ i, ∃ b ∈ B n, b + F ∈ B n) :
    ∀ L, ∃ j ≥ i, ∃ x, ∀ t < L, x + t ∈ A j := by
  intro L
  have hEne : E.Nonempty := by
    obtain ⟨e, he, -⟩ := hres 0 hF
    exact ⟨e, he⟩
  set U := E.max' hEne with hUdef
  obtain ⟨j, hji, base, hbase⟩ := finite_grid_of_pairs hfair hmono hanti hE hpairs (U + L)
  refine ⟨j, hji, base + U, fun t ht => ?_⟩
  set n := U + t with hndef
  obtain ⟨e, he, heq⟩ := hres (n % F) (Nat.mod_lt n hF)
  have heU : e ≤ U := Finset.le_max' E e he
  have hen : e ≤ n := by omega
  have hdvd : F ∣ (n - e) := (Nat.modEq_iff_dvd' hen).mp heq
  have hkdef : F * ((n - e) / F) = n - e := Nat.mul_div_cancel' hdvd
  have hkT : (n - e) / F ≤ U + L := by
    have h1 : (n - e) / F ≤ n - e := Nat.div_le_self _ _
    omega
  have hh := hbase e he ((n - e) / F) hkT
  have hfin : base + e + F * ((n - e) / F) = base + U + t := by
    rw [hkdef]; omega
  rwa [hfin] at hh

/-- Step 5, modular generation: given a finite `E ⊆ A i` and a multiset `S`
of prescribed residues each realizable in every later second component (a
witness the `KneserResidues` worker is responsible for constructing, e.g.
from finite-cyclic-group subset-sum coverage — *consumed* here, not
reproved), toggling `E`/`E ∪ (E + b)` once per element of `S` (absorbing the
current finite set before each toggle) produces a finite `E' ⊆ A j`
representing, modulo `F`, every `e + u` with `e ∈ E` and `u` an actual
subset sum of `S`. The multiset-cons case of `subsetSums` is exactly this
toggle: `subsetSums (δ ::ₘ S') = subsetSums S' ∪ (subsetSums S').image (δ+·)`. -/
theorem realization_of_modular_subset_sums {A B : ℕ → Set ℕ} {F i : ℕ} {E : Finset ℕ}
    (hfair : FairAbsorption A B) (hmono : Monotone A) (hanti : Antitone B)
    (hE : ∀ e ∈ E, e ∈ A i) (S : Multiset ℕ)
    (hS : ∀ n ≥ i, ∀ δ ∈ S, ∃ b ∈ B n, b % F = δ % F) :
    ∃ j ≥ i, ∃ E' : Finset ℕ, (∀ e' ∈ E', e' ∈ A j) ∧
      ∀ u ∈ subsetSums S, ∀ e ∈ E, ∃ e' ∈ E', e' % F = (e + u) % F := by
  classical
  induction S using Multiset.induction_on with
  | empty =>
    refine ⟨i, le_rfl, E, hE, fun u hu e he => ?_⟩
    have hu0 : u = 0 := by simpa using hu
    exact ⟨e, he, by simp [hu0]⟩
  | cons δ S' ih =>
    have hS' : ∀ n ≥ i, ∀ δ' ∈ S', ∃ b ∈ B n, b % F = δ' % F := by
      intro n hn δ' hδ'
      exact hS n hn δ' (Multiset.mem_cons_of_mem hδ')
    obtain ⟨j, hji, E'', hE'', hrep⟩ := ih hS'
    obtain ⟨l, hlj, hl⟩ := finite_absorption hfair hmono hanti j E'' hE''
    obtain ⟨b, hb, hbmod⟩ := hS l (hji.trans hlj) δ (Multiset.mem_cons_self δ S')
    set E3 : Finset ℕ := E'' ∪ E''.image (· + b) with hE3def
    have hE3mem : ∀ e' ∈ E3, e' ∈ A l := by
      intro e' he'
      rcases Finset.mem_union.mp he' with h1 | h1
      · exact hmono hlj (hE'' e' h1)
      · obtain ⟨e'', he'', rfl⟩ := Finset.mem_image.mp h1
        exact hl e'' he'' b hb
    refine ⟨l, hji.trans hlj, E3, hE3mem, fun u hu e he => ?_⟩
    rw [subsetSums_cons] at hu
    rcases Finset.mem_union.mp hu with hu | hu
    · obtain ⟨e'', he'', heq⟩ := hrep u hu e he
      exact ⟨e'', Finset.mem_union.mpr (Or.inl he''), heq⟩
    · obtain ⟨u', hu', rfl⟩ := Finset.mem_image.mp hu
      obtain ⟨e'', he'', heq⟩ := hrep u' hu' e he
      refine ⟨e'' + b, Finset.mem_union.mpr (Or.inr (Finset.mem_image.mpr ⟨e'', he'', rfl⟩)), ?_⟩
      have h1 : Nat.ModEq F e'' (e + u') := heq
      have h2 : Nat.ModEq F b δ := hbmod
      have h3 : Nat.ModEq F (e'' + b) ((e + u') + δ) := h1.add h2
      have h4 : (e + u') + δ = e + (δ + u') := by ring
      rwa [h4] at h3

end Erdos1112.Proof.Short.KneserDensity
