#!/usr/bin/env python3
"""Generate the LaTeX certificate tables (Appendix B) from data/certificate-data.md.

The tables are the finite layer of the (SHARP) proof; they are also transcribed into
Lean (Sharp/TablesData.lean) and checked by the kernel. Typesetting them by hand would
risk a silent divergence between the printed paper and the checked data, so we parse the
canonical markdown source and emit LaTeX, and we re-verify every emitted row here:

  budget  x + Y + Z <= M - 1
  coverage  subset-sums of {x*a, Y*b, Z*M} contain M consecutive integers

Any row failing either check aborts the build.
"""
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent
SRC = OUT / "data" / "certificate-data.md"

ROW_A = re.compile(r"\((\d+),(\d+),(\d+)\)\s*(?:→|->)\s*\((\d+),(\d+),(\d+)\)")
ROW_B = re.compile(
    r"\[(\d+);(\d+),(\d+)\]\s*\((\d+),(\d+),(\d+)\)\s*(?:→|->)\s*\((\d+),(\d+),(\d+)\)"
)


def code_blocks(text):
    return re.findall(r"```\n(.*?)```", text, re.S)


def subset_sums_cover(a, b, M, x, Y, Z):
    """Exact bitmask subset-sum: do the sums of the multiset contain M consecutive ints?"""
    mask = 1
    for val, cnt in ((a, x), (b, Y), (M, Z)):
        for _ in range(cnt):
            mask |= mask << val
    run = (1 << M) - 1  # M consecutive integers
    # slide: does `mask` contain M consecutive set bits anywhere?
    shifted = mask
    for _ in range(M - 1):
        mask &= mask >> 1
    return mask != 0, shifted


def check(a, b, M, x, Y, Z):
    errs = []
    if x + Y + Z > M - 1:
        errs.append(f"budget {x+Y+Z} > M-1 = {M-1}")
    ok, _ = subset_sums_cover(a, b, M, x, Y, Z)
    if not ok:
        errs.append(f"subset sums of ({x}x{a}, {Y}x{b}, {Z}x{M}) lack {M} consecutive")
    return errs


def main():
    text = SRC.read_text(encoding="utf-8")
    blocks = code_blocks(text)
    if len(blocks) < 2:
        sys.exit(f"expected >=2 code blocks in {SRC}, found {len(blocks)}")

    rows_a = ROW_A.findall(blocks[0])
    rows_b = ROW_B.findall(blocks[1])
    rows_a = [tuple(map(int, r)) for r in rows_a]
    rows_b = [tuple(map(int, r)) for r in rows_b]

    print(f"parsed Table A: {len(rows_a)} rows; Table B: {len(rows_b)} rows")

    # ---- hard structural assertions (a silently dropped/malformed row must abort) ----
    EXPECT_A, EXPECT_B = 172, 178
    if len(rows_a) != EXPECT_A:
        sys.exit(f"ABORT: expected {EXPECT_A} Table-A rows, parsed {len(rows_a)}")
    if len(rows_b) != EXPECT_B:
        sys.exit(f"ABORT: expected {EXPECT_B} Table-B classes, parsed {len(rows_b)}")
    if len(set(rows_a)) != len(rows_a):
        sys.exit("ABORT: duplicate Table-A rows")
    class_keys = [(a, eb, h) for (a, eb, h, *_rest) in rows_b]
    if len(set(class_keys)) != len(class_keys):
        sys.exit("ABORT: duplicate Table-B class key (a, ebar, h)")
    # class metadata must agree with each base triple: base a == class a, h == M - b,
    # and ebar == (b - a) mod a (the reduced excess of the base member)
    for (a, eb, h, ba, bb, bM, x, Y, Z) in rows_b:
        if ba != a:
            sys.exit(f"ABORT: class [{a};{eb},{h}] base a={ba} != class a={a}")
        if bM - bb != h:
            sys.exit(f"ABORT: class [{a};{eb},{h}] base M-b={bM-bb} != h={h}")
        if (bb - ba) % a != eb:
            sys.exit(f"ABORT: class [{a};{eb},{h}] base (b-a) mod a={(bb-ba)%a} != ebar={eb}")

    failures = 0
    for (a, b, M, x, Y, Z) in rows_a:
        for e in check(a, b, M, x, Y, Z):
            print(f"  TABLE A FAIL ({a},{b},{M})->({x},{Y},{Z}): {e}")
            failures += 1
    for (a, ebar, h, b_, bb, MM, x, Y, Z) in rows_b:
        for e in check(b_, bb, MM, x, Y, Z):
            print(f"  TABLE B FAIL [{a};{ebar},{h}] ({b_},{bb},{MM})->({x},{Y},{Z}): {e}")
            failures += 1

    if failures:
        sys.exit(f"ABORT: {failures} certificate row(s) failed re-verification")
    print("all rows re-verified: budget <= M-1 and coverage of M consecutive integers")

    # ---- emit Table A ----
    cols = 4
    with (OUT / "table-a.tex").open("w", encoding="utf-8") as f:
        f.write("% GENERATED by gen-tables.py -- do not edit by hand.\n")
        f.write("{\\small\n")
        f.write("\\begin{longtable}{" + "l@{\\quad}" * (cols - 1) + "l}\n")
        f.write("\\caption{The $%d$ exceptional Case-T triples (the T-tail lemma of the main paper),\n"
                "all with $a \\le 29$; the scan over $a \\le 3000$ finds no others.\n"
                "Format $(a,b,M) \\to (x,Y,Z)$: the multiset of $x$ copies of $a$, $Y$ of $b$,\n"
                "$Z$ of $M$.}\\label{tab:A}\\\\\n" % len(rows_a))
        f.write("\\endfirsthead\n\\caption[]{\\emph{(continued)}.}\\\\\n\\endhead\n")
        for i in range(0, len(rows_a), cols):
            chunk = rows_a[i:i + cols]
            cells = [
                "$(%d,%d,%d)\\!\\to\\!(%d,%d,%d)$" % r for r in chunk
            ]
            cells += [""] * (cols - len(cells))
            f.write(" & ".join(cells) + " \\\\\n")
        f.write("\\end{longtable}\n}\n")

    # ---- emit Table B ----
    cols = 3
    with (OUT / "table-b.tex").open("w", encoding="utf-8") as f:
        f.write("% GENERATED by gen-tables.py -- do not edit by hand.\n")
        f.write("{\\small\n")
        f.write("\\begin{longtable}{" + "l@{\\quad}" * (cols - 1) + "l}\n")
        f.write("\\caption{The $%d$ Case-B class bases ($a \\le 11$, $\\mu \\ge 12$).\n"
                "Format $[a;\\bar e,h]$ followed by the base triple $(a,b,M) \\to (x,Y,Z)$.\n"
                "The $\\lambda$-lift lemma of the main paper extends each certificate to every member\n"
                "of its class with larger $e$.}\\label{tab:B}\\\\\n" % len(rows_b))
        f.write("\\endfirsthead\n\\caption[]{\\emph{(continued)}.}\\\\\n\\endhead\n")
        for i in range(0, len(rows_b), cols):
            chunk = rows_b[i:i + cols]
            cells = [
                "$[%d;%d,%d]\\,(%d,%d,%d)\\!\\to\\!(%d,%d,%d)$" % r for r in chunk
            ]
            cells += [""] * (cols - len(cells))
            f.write(" & ".join(cells) + " \\\\\n")
        f.write("\\end{longtable}\n}\n")

    print(f"wrote {OUT/'table-a.tex'} and {OUT/'table-b.tex'}")
    emit_csv(rows_a, rows_b)


def emit_csv(rows_a, rows_b):
    """Machine-readable exports of the certificate data (referee-auditable).

    Every row is re-verified before emission (see check()), so the CSVs, the printed
    LaTeX tables, and the rows the Lean kernel decides all derive from one source.
    """
    import csv, hashlib
    data = OUT / "data"
    data.mkdir(exist_ok=True)

    with (data / "table-A.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["a", "b", "M", "x", "Y", "Z", "budget", "M_minus_1", "e", "h"])
        for (a, b, M, x, Y, Z) in rows_a:
            w.writerow([a, b, M, x, Y, Z, x + Y + Z, M - 1, b - a, M - b])

    with (data / "table-B.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["a", "ebar", "h", "base_a", "base_b", "base_M", "x", "Y", "Z",
                    "budget", "M_minus_1"])
        for (a, eb, h, ba, bb, bM, x, Y, Z) in rows_b:
            w.writerow([a, eb, h, ba, bb, bM, x, Y, Z, x + Y + Z, bM - 1])

    lines = []
    for name in ("table-A.csv", "table-B.csv"):
        digest = hashlib.sha256((data / name).read_bytes()).hexdigest()
        lines.append(f"{digest}  data/{name}")
    (data / "SHA256SUMS").write_text("\n".join(lines) + "\n")

    printed_total = len(rows_a) + len(rows_b)
    (data / "MANIFEST.md").write_text(f"""# Certificate data manifest

Generated by `gen-tables.py`. Every row below was re-verified at generation time:
`budget = x + Y + Z <= M - 1`, and the subset sums of the multiset (x copies of a,
Y of b, Z of M) contain M consecutive integers, by exact bitmask.

| Dataset | Distinct rows printed in the paper | Role |
|---|---:|---|
| Table A (`table-A.csv`) | {len(rows_a)} | Case-T exceptional triples (mu <= 11), all with a <= 29 |
| Table B (`table-B.csv`) | {len(rows_b)} | Case-B class bases (a <= 11, mu >= 12); extended by the lambda-lift |

Case P contributes NO certificate rows: it is closed in prose (one closed-form
multiset for the whole line, plus the single triple (3,4,5) checked inline).

## Printed rows vs kernel rows (the paper's Section 6 reconciliation)

The paper and the Lean development follow ONE route through Case T, so Table A is the
same {len(rows_a)} rows in both. Table B differs only by a transcription artifact: the
kernel decides a 30-row supplement on top of the {len(rows_a)} main rows, of which 24
duplicate main rows and 6 are new bases (the six diagonal ebar = h classes), so
{len(rows_a)} + 6 = {len(rows_b)} DISTINCT classes are what the paper prints.

| | Printed | Kernel rows |
|---|---:|---:|
| Table A (Case T) | {len(rows_a)} | {len(rows_a)} |
| Table B (Case B) | {len(rows_b)} | 202 |
| Case P | 0 | 0 |
| **Total** | **{printed_total}** | **374** |

The {printed_total}-vs-374 difference is exactly the 24 duplicated Table-B rows
({len(rows_b)} printed classes + 24 duplicates + Table A's {len(rows_a)} = 374).
""")
    print(f"wrote {data}/table-A.csv, table-B.csv, SHA256SUMS, MANIFEST.md")


if __name__ == "__main__":
    main()
